title: Bioinformatics Spring School 2020
email: carpentries@otago.ac.nz
baseurl: "/bioinformatics-spring-school-2020/"
url: "https://otagocarpentries.github.io"
theme: jekyll-theme-leap-day

day1_url: "day1.html"
